// Create User Process
export const CREATE_USER_REQ = 'CREATE_USER_REQ';
export const CREATE_USER_COMPLETE = 'CREATE_USER_COMPLETE';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';


// Login Process
export const SEARCH_USER_START = 'SEARCH_USER_START';
export const SEARCH_USER_ERROR = 'SEARCH_USER_ERROR';
export const SEARCH_USER_COMPLETE = 'SEARCH_USER_COMPLETE';
export const SEARCH_USER_RESET = 'SEARCH_USER_RESET';

export const SEARCH_SERVICES_START = 'SEARCH_SERVICES_START';
export const SEARCH_SERVICES_ERROR = 'SEARCH_SERVICES_ERROR';
export const SEARCH_SERVICES_COMPLETE = 'SEARCH_SERVICES_COMPLETE';
export const SEARCH_SERVICES_RESET = 'SEARCH_SERVICES_RESET';