export const SEARCH_USER_START = 'SEARCH_USER_START';
export const SEARCH_USER_ERROR = 'SEARCH_USER_ERROR';
export const SEARCH_USER_COMPLETE = 'SEARCH_USER_COMPLETE';
export const SEARCH_USER_RESET = 'SEARCH_USER_RESET';

export const SEARCH_SERVICES_START = 'SEARCH_SERVICES_START';
export const SEARCH_SERVICES_ERROR = 'SEARCH_SERVICES_ERROR';
export const SEARCH_SERVICES_COMPLETE = 'SEARCH_SERVICES_COMPLETE';
export const SEARCH_SERVICES_RESET = 'SEARCH_SERVICES_RESET';